### ISSUE TITLE
Whats going on with default border color?

### ISSUE THREAD

**Issue by smathson** [FieldLevel/FieldLevelPlaybook#100]
It comes from what appears to be a tailwind-generated block in our `index.css` file. It's essentially our default color for borders.

Here's the block:

```css
/**
 * 1. Prevent padding and border from affecting element width.
 *
 *    We used to set this in the html element and inherit from
 *    the parent element for everything else. This caused issues
 *    in shadow-dom-enhanced elements like <details> where the content
 *    is wrapped by a div with box-sizing set to `content-box`.
 *
 *    https://github.com/mozdevs/cssremedy/issues/4
 *
 *
 * 2. Allow adding a border to an element by just adding a border-width.
 *
 *    By default, the way the browser specifies that an element should have no
 *    border is by setting it's border-style to `none` in the user-agent
 *    stylesheet.
 *
 *    In order to easily add borders to elements by just setting the `border-width`
 *    property, we change the default border-style for all elements to `solid`, and
 *    use border-width to hide them instead. This way our `border` utilities only
 *    need to set the `border-width` property instead of the entire `border`
 *    shorthand, making our border utilities much more straightforward to compose.
 *
 *    https://github.com/tailwindcss/tailwindcss/pull/116
 */

*,
    ::before,
    ::after {
        box-sizing: border-box; /* 1 */
        border-width: 0; /* 2 */
        border-style: solid; /* 2 */
        border-color: #e5e7eb; /* 2 */
    }

```
    
   I know we have "border-base", but that doesn't appear to be the same color when I examine in dev tools (using auto conversion between rgba and hex). Anyway, the idea was just to keep the borders consistent between the two variants (when visible)

_Originally posted by @funktr0n in https://github.com/FieldLevel/FieldLevel/pull/5841#discussion_r1176755599_
